version: "3"
services:
  # redis:
  #   image: redis:latest
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./init/2-init.sql:/docker-entrypoint-initdb.d/2-init.sql
  elasticsearch:
    # image: elasticsearch:8.8.1
    image: elasticsearch:7.17.10
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=123456
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false

  kibana:
    # image: kibana:8.8.1
    image: kibana:7.17.10
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  # web-admin_1:
  #   image: web-admin:v1
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   depends_on:
  #     - redis
  #     - db
  # web-admin_2:
  #   image: web-admin:v1
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   depends_on:
  #     - redis
  #     - db
  # web-user:
  #   image: web-user:v1
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   depends_on:
  #     - redis
  #     - db
  # nginx-proxy:
  #   image: nginx-proxy:v1
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - web-admin_1
  #     - web-admin_2
  #     - web-user
