import { ThemeProvider } from '@/libs/emotion';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { muiTheme } from '@/styles/theme';
import { store } from '@/redux/store';
import { ReduxProvider } from '@/redux/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className={inter.className}>
        <ReduxProvider>
          <ThemeProvider theme={muiTheme}>{children}</ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
