server:
  servlet:
    session:
      cookie:
        name: "SESSION_USER"
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/lab_project
    username: dev1
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    rest:
      uris: "http://localhost:9200"
      username: elastic
      password: 123456

logging:
  level:
    org.springframework.web: TRACE
    org.springframework.security: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    demo.lab: DEBUG
