--insert into accounts (id, email, password) values (1, 'admin@mail.com', '$2a$10$Hqd3.moyT0uKB.jHEBGoJOag8l.nneI1t/IHyvEBy2jE4BxDRilaK');
---- 123456
--insert into accounts (id, email, password) values (2, 'user@mail.com', '$2a$10$Hqd3.moyT0uKB.jHEBGoJOag8l.nneI1t/IHyvEBy2jE4BxDRilaK');
--insert into roles (account_id, role) values(1, 'ADMIN');
--insert into roles (account_id, role) values(2, 'USER');