spring:
  port: 8787
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/lab_project
    username: dev1
    password: 123456
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    rest:
      uris: http://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:5432}
      password: elastic
      username: 123456
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false